# Generated by Django 4.2.6 on 2023-10-27 14:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terceiro', models.CharField(max_length=200)),
                ('contacto', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('saldo_contabilidade', models.CharField(max_length=50)),
                ('saldo', models.TextField(blank=True)),
                ('arquivo', models.FileField(blank=True, upload_to='arquivos/')),
                ('link_unico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('extrato', models.BooleanField(default=False)),
            ],
        ),
    ]
