# Generated by Django 4.2.7 on 2023-11-15 17:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('confirm_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(max_length=50)),
                ('cliente_codigo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement_nome', models.CharField(max_length=50)),
                ('engagement_referencia', models.CharField(max_length=50)),
                ('pdf_assinado', models.FileField(blank=True, null=True, upload_to='pdfs_assinados/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confirm_app.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoTerceiros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terceiro', models.CharField(max_length=200)),
                ('contacto', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('conta_contabilidade_cliente', models.CharField(max_length=200)),
                ('conta_contabilidade_cliente_titulos', models.CharField(max_length=200)),
                ('conta_contabilidade_fornecedor', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('conta_contabilidade_fornecedor_titulos', models.CharField(max_length=200)),
                ('conta_contabilidade_odc', models.CharField(max_length=200)),
                ('conta_contabilidade_outros', models.CharField(max_length=200)),
                ('saldo_contabilidade_cliente', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('saldo_contabilidade_cliente_titulos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('saldo_contabilidade_fornecedor', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('saldo_contabilidade_fornecedor_titulos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('saldo_contabilidade_odc', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('saldo_contabilidade_outros', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('saldo_resposta_cliente', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('saldo_resposta_cliente_titulos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('saldo_resposta_fornecedor', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('saldo_resposta_fornecedor_titulos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('saldo_resposta_odc', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('saldo_resposta_outros', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('anexo', models.FileField(blank=True, upload_to='arquivos/')),
                ('link_unico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('primeiro_envio', models.DateTimeField()),
                ('ultimo_envio', models.DateTimeField()),
                ('respondido', models.DateTimeField()),
                ('conciliado', models.BooleanField(default=False)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confirm_app.engagement')),
            ],
        ),
        migrations.DeleteModel(
            name='Registro',
        ),
    ]
