# Generated by Django 4.2.6 on 2023-10-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confirm_app', '0002_remove_registro_extrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='extrato',
            field=models.BooleanField(default=False),
        ),
    ]
