# Generated by Django 4.2.7 on 2023-11-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confirm_app', '0002_cliente_engagement_pedidoterceiros_delete_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoterceiros',
            name='primeiro_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoterceiros',
            name='respondido',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoterceiros',
            name='ultimo_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
