# Generated by Django 4.2.1 on 2023-11-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confirm_app', '0003_alter_pedidoterceiros_primeiro_envio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidoterceiros',
            old_name='anexo',
            new_name='anexo_resposta_cliente',
        ),
        migrations.RenameField(
            model_name='pedidoterceiros',
            old_name='conciliado',
            new_name='conciliado_cliente',
        ),
        migrations.AddField(
            model_name='pedidoterceiros',
            name='anexo_resposta_cliente_titulos',
            field=models.FileField(blank=True, upload_to='arquivos/'),
        ),
        migrations.AddField(
            model_name='pedidoterceiros',
            name='anexo_resposta_fornecedor',
            field=models.FileField(blank=True, upload_to='arquivos/'),
        ),
        migrations.AddField(
            model_name='pedidoterceiros',
            name='anexo_resposta_fornecedor_titulos',
            field=models.FileField(blank=True, upload_to='arquivos/'),
        ),
        migrations.AddField(
            model_name='pedidoterceiros',
            name='anexo_resposta_odc',
            field=models.FileField(blank=True, upload_to='arquivos/'),
        ),
        migrations.AddField(
            model_name='pedidoterceiros',
            name='anexo_resposta_outros',
            field=models.FileField(blank=True, upload_to='arquivos/'),
        ),
        migrations.AddField(
            model_name='pedidoterceiros',
            name='conciliado_cliente_titulos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedidoterceiros',
            name='conciliado_fornecedor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedidoterceiros',
            name='conciliado_fornecedor_titulos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedidoterceiros',
            name='conciliado_odc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedidoterceiros',
            name='conciliado_outros',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedidoterceiros',
            name='movsctb_cliente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='pedidoterceiros',
            name='movsctb_cliente_titulos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='pedidoterceiros',
            name='movsctb_fornecedor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='pedidoterceiros',
            name='movsctb_fornecedor_titulos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='pedidoterceiros',
            name='movsctb_odc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='pedidoterceiros',
            name='movsctb_outros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='pedidoterceiros',
            name='movsterceiro_cliente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='pedidoterceiros',
            name='movsterceiro_cliente_titulos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='pedidoterceiros',
            name='movsterceiro_fornecedor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='pedidoterceiros',
            name='movsterceiro_fornecedor_titulos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='pedidoterceiros',
            name='movsterceiro_odc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='pedidoterceiros',
            name='movsterceiro_outros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
