# Generated by Django 4.2.7 on 2023-11-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confirm_app', '0004_alter_registro_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='arquivo',
            field=models.FileField(blank=True, upload_to='arquivos/'),
        ),
    ]
