# Generated by Django 4.2.1 on 2023-11-05 23:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('confirm_app', '0006_engagement_registro_engagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='autorizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registro',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Autorizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autorizador', models.CharField(max_length=200)),
                ('data_de_autorizacao', models.DateTimeField(auto_now_add=True)),
                ('ip_autorizador', models.GenericIPAddressField(blank=True, null=True)),
                ('link_unico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('confirmado', models.BooleanField(default=False)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confirm_app.engagement')),
                ('registros_autorizados', models.ManyToManyField(related_name='autorizacoes', to='confirm_app.registro')),
            ],
        ),
    ]
