# Generated by Django 4.2.1 on 2023-11-05 23:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('confirm_app', '0007_registro_autorizado_registro_confirmado_autorizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizacao',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
