# Generated by Django 4.2.6 on 2023-11-13 12:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('confirm_app', '0008_autorizacao_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(max_length=50)),
                ('cliente_codigo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PedidoTerceiros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terceiro', models.CharField(max_length=200)),
                ('conta_contabilidade', models.CharField(max_length=50)),
                ('contacto', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('saldo_contabilidade', models.CharField(max_length=50)),
                ('saldo', models.TextField(blank=True)),
                ('anexo', models.FileField(blank=True, upload_to='arquivos/')),
                ('link_unico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('respondido', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='registro',
            name='engagement',
        ),
        migrations.RenameField(
            model_name='engagement',
            old_name='referencia',
            new_name='engagement_nome',
        ),
        migrations.AddField(
            model_name='engagement',
            name='engagement_referencia',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Autorizacao',
        ),
        migrations.DeleteModel(
            name='Registro',
        ),
        migrations.AddField(
            model_name='pedidoterceiros',
            name='engagement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confirm_app.engagement'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confirm_app.cliente'),
        ),
    ]
