# Generated by Django 4.2.6 on 2023-11-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confirm_app', '0009_cliente_pedidoterceiros_remove_registro_engagement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='pdf_assinados',
            field=models.FileField(blank=True, null=True, upload_to='pdfs_assinados/'),
        ),
    ]
