# Generated by Django 4.2.6 on 2023-11-14 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confirm_app', '0010_engagement_pdf_assinados'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engagement',
            old_name='pdf_assinados',
            new_name='pdf_assinado',
        ),
    ]
